// Package agent defines the Driver contract used by clonectl to talk to
// remote data-plane agents (e.g. redis-shake-agent). Each agent is a
// black-box executor that forks upstream CLI tools (RedisShake /
// RedisFullCheck / ...) on its own host; clonectl only knows the Driver
// interface and the Submit/Status/Stop/Logs/Metrics envelope.
//
// Design goals:
//   - clonectl never imports or links against upstream tool code.
//   - Upstream version drift is absorbed by the agent process, not by
//     clonectl. Renaming an upstream flag or TOML key only touches the
//     agent (argvgen.go / tomlgen.go).
//   - New tools plug in via Driver.Register() with no changes to the
//     scheduler / runner / UI / alert paths.
package agent

import (
	"context"
	"encoding/json"
	"fmt"
)

// ToolKind identifies which upstream tool family a driver handles.
// Adding a new kind requires (a) defining the constant, (b) implementing
// a Driver, and (c) Register()-ing it in internal/agent/registry.go init.
type ToolKind string

const (
	// ToolRedisShake wraps tair-opensource/RedisShake (sync / restore /
	// dump / rump modes; PSYNC + RDB + SCAN pipelines).
	ToolRedisShake ToolKind = "redis-shake"

	// ToolRedisFullCheck wraps tair-opensource/RedisFullCheck
	// (4-compare-mode verification between source & target Redis).
	ToolRedisFullCheck ToolKind = "redis-fullcheck"
)

// IsValid reports whether k is a registered ToolKind. The Registry may
// reject unknown kinds even if IsValid returns true (driver not wired).
func (k ToolKind) IsValid() bool {
	switch k {
	case ToolRedisShake, ToolRedisFullCheck:
		return true
	default:
		return false
	}
}

// Spec is the tool-agnostic task description. Drivers translate Spec
// into the upstream tool's native configuration (TOML, argv, ...).
type Spec struct {
	// Source describes the upstream connection / origin side.
	Source Endpoint `json:"source"`
	// Target describes the downstream connection / destination side.
	// Empty for tools that have no target (e.g. dump mode).
	Target Endpoint `json:"target,omitempty"`
	// Mode is the tool-specific sub-mode (e.g. "sync_reader",
	// "rdb_reader", "scan_reader", or compare_mode int as string).
	Mode string `json:"mode"`
	// Extra passes any tool-specific knobs without driver knowledge.
	Extra json.RawMessage `json:"extra,omitempty"`
}

// Endpoint describes a single connection endpoint.
type Endpoint struct {
	// Mode is the deployment topology: "standalone" | "cluster" |
	// "sentinel" | "proxy". Driver validates against its tool's
	// supported topologies.
	Mode string `json:"mode"`
	// Addresses is the list of host:port pairs. For cluster / sentinel
	// this is the seed list; for standalone the single entry.
	Addresses []string `json:"addresses"`
	// MasterName is required when Mode == "sentinel".
	MasterName string `json:"master_name,omitempty"`
	// DB is the logical database index (0..15 for Redis).
	DB int `json:"db,omitempty"`
	// Username is the ACL username (Redis 6+).
	Username string `json:"username,omitempty"`
	// KeyPrefix narrows sync/verify to a single prefix (Redis only).
	KeyPrefix string `json:"key_prefix,omitempty"`
}

// Secrets are short-lived credentials injected into the agent process
// at submit time. The Driver never persists Secrets to its own state —
// it forwards them to the upstream tool, then zeros them in memory.
//
// v1 transport: HTTPS + (optional) shared secret. The agent is
// expected to feed Secrets directly into TOML / argv without ever
// writing them to disk.
type Secrets struct {
	SourcePassword string `json:"source_password,omitempty"`
	TargetPassword string `json:"target_password,omitempty"`
}

// SubmitRequest is the wire shape sent to /v1/tasks/submit on the agent.
type SubmitRequest struct {
	// Tool is the upstream family (ToolKind). Agent may reject if its
	// configured binary does not support this tool.
	Tool ToolKind `json:"tool"`

	// TaskID is generated by clonectl and treated as opaque by the
	// agent. Used as the audit/log/key identifier across the system.
	TaskID string `json:"task_id"`

	// Mode is tool-specific: for ToolRedisShake one of
	// "sync_reader"|"rdb_reader"|"scan_reader"; for ToolRedisFullCheck
	// one of "1"|"2"|"3"|"4" (compare modes).
	Mode string `json:"mode"`

	// Spec carries the tool-agnostic connection + key shape.
	Spec Spec `json:"spec"`

	// Secrets are credentials. The driver hands them to the agent
	// out-of-band of Spec so the agent can scrub Spec from logs without
	// also scrubbing the connection shape.
	Secrets Secrets `json:"secrets,omitempty"`

	// LogRetentionDays tells the agent how long to keep stdout/stderr
	// log files and result.db before garbage collection.
	LogRetentionDays int `json:"log_retention_days,omitempty"`
}

// SubmitResponse is the agent's reply to a successful Submit.
type SubmitResponse struct {
	TaskID    string `json:"task_id"`
	PID       int    `json:"pid"`
	StartedAt int64  `json:"started_at_unix_ms"`
	State     string `json:"state"` // "queued" | "running"
}

// TaskState is the normalized lifecycle. Every driver maps its upstream
// private states to one of these.
type TaskState string

const (
	StateQueued     TaskState = "queued"
	StateRunning    TaskState = "running"
	StateSuccess    TaskState = "success"
	StateFailed     TaskState = "failed"
	StateStopped    TaskState = "stopped"
	StateUnknown    TaskState = "unknown"
	StateUnreachable TaskState = "agent_unreachable" // agent ping failed
	StateUnsupported TaskState = "unsupported_mode"  // upstream no longer ships this mode
)

// TaskStatus is the normalized snapshot returned to clonectl on every
// Status() call. RawProgress carries tool-private metrics (e.g.
// redis-shake's `total/finished/percent`); TranslateProgress converts
// it into the UI-friendly NormalizedProgress.
type TaskStatus struct {
	TaskID    string          `json:"task_id"`
	State     TaskState       `json:"state"`
	PID       int             `json:"pid,omitempty"`
	ExitCode  int             `json:"exit_code,omitempty"`
	Error     string          `json:"error,omitempty"`
	StartedAt int64           `json:"started_at_unix_ms,omitempty"`
	EndedAt   int64           `json:"ended_at_unix_ms,omitempty"`
	Raw       json.RawMessage `json:"raw,omitempty"`
}

// LogsOpts controls tail/range for /v1/tasks/logs.
type LogsOpts struct {
	// Offset is the byte offset to start reading from (0 = from start).
	Offset int64 `json:"offset,omitempty"`
	// Limit is the max number of bytes to return (0 = unlimited up to
	// agent's chunk cap).
	Limit int `json:"limit,omitempty"`
	// Stream is "stdout" or "stderr"; agent concatenates by default.
	Stream string `json:"stream,omitempty"`
}

// LogsChunk is a contiguous slice of the task's stdout/stderr stream.
type LogsChunk struct {
	TaskID  string `json:"task_id"`
	Offset  int64  `json:"offset"`  // next offset to request
	Content []byte `json:"content"` // raw bytes (UTF-8 expected)
	EOF     bool   `json:"eof"`     // process has exited & log is closed
}

// ListFilter narrows /v1/tasks/list responses.
type ListFilter struct {
	Tool ToolKind `json:"tool,omitempty"`
}

// TaskSummary is the lightweight row in a List response.
type TaskSummary struct {
	TaskID    string    `json:"task_id"`
	Tool      ToolKind  `json:"tool"`
	State     TaskState `json:"state"`
	PID       int       `json:"pid,omitempty"`
	StartedAt int64     `json:"started_at_unix_ms,omitempty"`
}

// MetricsSnapshot is a one-shot scrape of the task's metrics endpoint.
// Format is tool-defined; clonectl treats it as opaque unless
// TranslateProgress can extract counters.
type MetricsSnapshot struct {
	TaskID  string          `json:"task_id"`
	Content json.RawMessage `json:"content"` // Prometheus text or JSON
}

// RawProgress is the tool-private progress payload embedded in
// TaskStatus.Raw. Each driver defines its own struct and passes it via
// TranslateProgress.
type RawProgress struct {
	// Tool is the upstream family for type-switching in the translator.
	Tool ToolKind `json:"tool"`
	// Payload is tool-private (e.g. {total, finished, percent} for
	// RedisShake or {round, processed, conflicts} for FullCheck).
	Payload json.RawMessage `json:"payload"`
}

// NormalizedProgress is the UI-friendly projection. clonectl's frontend
// renders one shape regardless of upstream tool.
type NormalizedProgress struct {
	// Total is the unit count the task intends to process (e.g. total
	// keys for a sync). Zero means unknown / N/A.
	Total int64 `json:"total"`
	// Done is the count finished so far.
	Done int64 `json:"done"`
	// Percent is Done / Total clamped to [0, 100]; -1 if unknown.
	Percent int `json:"percent"`
	// Throughput is ops/sec averaged over the recent poll window.
	Throughput float64 `json:"throughput"`
	// LagSeconds is the freshness lag (e.g. PSYNC offset lag) when the
	// tool exposes one. 0 means N/A.
	LagSeconds float64 `json:"lag_seconds"`
	// Stage is a free-form human label ("full_sync" | "incremental" |
	// "round_2_of_3" | ...).
	Stage string `json:"stage,omitempty"`
}

// Driver is the single contract every agent implements. The Registry
// routes (tool_kind, agent_endpoint) → Driver; the Scheduler / Runner
// only ever talk to Driver, never to agent endpoints directly.
//
// Drivers MUST be safe for concurrent use: clonectl may invoke Submit
// and Status in parallel from different goroutines (one task's submit
// vs another task's polling).
type Driver interface {
	// Kind returns the ToolKind this driver handles.
	Kind() ToolKind

	// ValidateSpec is a synchronous local check called before Submit
	// to avoid a wasted network round-trip. It MUST enforce:
	//   - Spec.Mode is supported by this driver
	//   - Endpoint.Mode × Topology is consistent
	//   - Required fields (Addresses, MasterName for sentinel, ...) are set
	ValidateSpec(spec Spec) error

	// Submit forwards the request to the remote agent and returns the
	// task_id confirmation. It does NOT block until the task completes —
	// the agent runs the upstream tool asynchronously.
	Submit(ctx context.Context, endpoint string, req SubmitRequest) (SubmitResponse, error)

	// Stop asks the agent to terminate a task. graceful=true lets the
	// agent SIGTERM and wait WaitDelay; graceful=false is SIGKILL.
	Stop(ctx context.Context, endpoint, taskID string, graceful bool) error

	// Status returns the latest snapshot. clonectl polls this every
	// PollInterval while the task is running.
	Status(ctx context.Context, endpoint, taskID string) (TaskStatus, error)

	// Logs streams the task's stdout/stderr. offset=0 starts from the
	// beginning; subsequent calls pass the returned Offset back.
	Logs(ctx context.Context, endpoint, taskID string, opts LogsOpts) (LogsChunk, error)

	// List returns lightweight task summaries on the remote agent.
	// Used at clonectl startup to reconcile orphaned tasks left by a
	// prior agent process that crashed mid-run.
	List(ctx context.Context, endpoint string, filter ListFilter) ([]TaskSummary, error)

	// Metrics scrapes the task's metrics endpoint (Prometheus text or
	// structured JSON depending on the upstream).
	Metrics(ctx context.Context, endpoint, taskID string) (MetricsSnapshot, error)

	// TranslateProgress converts the tool-private RawProgress into the
	// UI-friendly NormalizedProgress. Pure function — no I/O.
	TranslateProgress(raw RawProgress) NormalizedProgress
}

// DriverError is returned by Driver methods when the failure mode is
// actionable by clonectl (vs. transient network error).
type DriverError struct {
	// Code is a stable identifier (e.g. "invalid_spec",
	// "unsupported_mode", "agent_unreachable", "auth_failed").
	Code string
	// Message is the human-readable detail.
	Message string
	// Cause is the underlying error if any.
	Cause error
}

// Error implements the error interface.
func (e *DriverError) Error() string {
	if e.Cause != nil {
		return fmt.Sprintf("%s: %s: %v", e.Code, e.Message, e.Cause)
	}
	return fmt.Sprintf("%s: %s", e.Code, e.Message)
}

// Unwrap exposes the underlying cause for errors.Is / errors.As.
func (e *DriverError) Unwrap() error { return e.Cause }

// Common error codes returned by drivers.
const (
	ErrInvalidSpec     = "invalid_spec"
	ErrUnsupportedMode = "unsupported_mode"
	ErrAgentUnreachable = "agent_unreachable"
	ErrAuthFailed      = "auth_failed"
	ErrTaskNotFound    = "task_not_found"
	ErrUpstreamCrash   = "upstream_crash"
)

// NewDriverError builds a DriverError with an optional cause.
func NewDriverError(code, msg string, cause error) *DriverError {
	return &DriverError{Code: code, Message: msg, Cause: cause}
}
